export const GET_SESSION_TOKEN_REQUEST = 'GET_SESSION_TOKEN_REQUEST';
export const GET_SESSION_TOKEN_SUCCESS = 'GET_SESSION_TOKEN_SUCCESS';
export const GET_SESSION_TOKEN_FAILURE = 'GET_SESSION_TOKEN_FAILURE';
